# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gtaxl-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gtaxlwifi gtanotexlwifi gtaxllte gtanotexllte,$(TARGET_DEVICE)),)

endif
